
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iTech by ONDAMBA. KL KATABE, SC KIHILU, NANA A
 */
public class Chat extends javax.swing.JFrame {
    
    public static ServerSocket s;
    public static Socket socket;
    public static DataInputStream dis;
    public static DataOutputStream dout;
    Connection connection;
    PreparedStatement statement=null, state;
    ResultSet result=null;
    String URL="jdbc:mysql://localhost:3306/itech_project";
    String USER = "root";
    String PASSWORD = "Ced11@#01$";
    
    public void currentTime(){
       new javax.swing.Timer(0, new ActionListener() {
   @Override
   public void actionPerformed(ActionEvent e) {
   Date d = new Date();
   SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
   currentT.setText(s.format(d));
           }
           
       }
       
         ).start();
   }
    

    /**
     * Creates new form Chat
     */
    public static Connection getConnection() {
    Connection connection = null;
    PreparedStatement statement=null;
    ResultSet result=null;
    String URL="jdbc:mysql://localhost:3306/itech_project";
    String USER = "root";
    String PASSWORD = "Ced11@#01$";   
        try {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return connection;
      
    }
    public Chat() {
        initComponents();
        currentTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        textField1 = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        sendMessage = new javax.swing.JButton();
        msg_text = new java.awt.TextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        currentT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msg_area.setBackground(new java.awt.Color(204, 204, 204));
        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 500, 233));

        sendMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendMessage.setText("SEND");
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });
        getContentPane().add(sendMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 90, 50));

        msg_text.setBackground(new java.awt.Color(204, 204, 204));
        msg_text.setText("Message to send");
        msg_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msg_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msg_textFocusLost(evt);
            }
        });
        msg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_textActionPerformed(evt);
            }
        });
        msg_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_textKeyPressed(evt);
            }
        });
        getContentPane().add(msg_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 370, 50));

        backButton.setBackground(new java.awt.Color(153, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("EXIT");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmailPic.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 400));

        currentT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        currentT.setText("Time");
        getContentPane().add(currentT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("STUDENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        // TODO add your handling code here:
        try {
            String msg;
           /* msg = msg_text.getText();
            dout.writeUTF(msg);
            msg_text.setText(" "); */
            
            connection = getConnection();
           
            
            try{
                
             String sql = "INSERT INTO chat_tbl" + "(message_sent,message_received)"
            + "VALUES (?,?)";
             
            
             

            statement = connection.prepareStatement(sql);
            
                
            statement.setString(1, msg_text.getText());
            statement.setString(2, msg_area.getText());
            
          

            statement.executeUpdate(); 
           
          
             msg = msg_text.getText();
            dout.writeUTF(msg);
            msg_text.setText(" ");
            
            
          } catch (SQLException ex) {
      JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
        }catch (IOException ex){
            System.out.println(ex.getMessage());
        }
            
       
    }//GEN-LAST:event_sendMessageActionPerformed

    private void msg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_textActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_msg_textActionPerformed

    private void msg_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msg_textFocusGained
        if(msg_text.getText().equals("Message to send")){
           msg_text.setText("");
           msg_text.setForeground(new Color(51,51,51));
       }
    }//GEN-LAST:event_msg_textFocusGained

    private void msg_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msg_textFocusLost
        if(msg_text.getText().equals("")){
           msg_text.setText("Message to send");
           msg_text.setForeground(new Color(51,51,51));
       }
    }//GEN-LAST:event_msg_textFocusLost

    private void msg_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_textKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           try {
            String msg;
            msg = msg_text.getText();
            dout.writeUTF(msg);
            msg_text.setText(" ");
            
            }catch (IOException ex){
                System.out.println(ex.getMessage());
            }
           
       }
    }//GEN-LAST:event_msg_textKeyPressed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Chat is registered successfully");
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new HomeTutor().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
        
        String username = " ";
        String messageIn = " ";
         
        try{
            Scanner sc = new Scanner(System.in);
            
            socket = new Socket("192.168.8.157", 9191);
            System.out.println("Student: is connected..." + s);
            
            dis = new DataInputStream(socket.getInputStream());
            dout = new DataOutputStream(socket.getOutputStream());
            
            while(!messageIn.equals("exit")){
                messageIn = (String)dis.readUTF();
               //get the current user from the database 
                msg_area.setText(msg_area.getText() + "\n" + "Tutor: " + messageIn);
            }
            
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel currentT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private static javax.swing.JTextArea msg_area;
    private java.awt.TextField msg_text;
    private javax.swing.JButton sendMessage;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
