/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author acer
 */
public class Tutors extends javax.swing.JFrame {

    /**
     * Creates new form Tutors
     */
    
    public void currentTime(){
       new Timer(0, new ActionListener() {
       @Override
      public void actionPerformed(ActionEvent e) {
     Date d = new Date();
     SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
    currentT.setText(s.format(d));
           }
           
       }
       
         ).start();
   }
    public Tutors() {
        initComponents();
        currentTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lecturer1Button = new javax.swing.JButton();
        lecturer2Button = new javax.swing.JButton();
        lecturer3Button = new javax.swing.JButton();
        lecturer4Button = new javax.swing.JButton();
        currentT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  SELECT THE TUTOR YOU WOULD LIKE TO TALK TO :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 43));

        lecturer1Button.setBackground(new java.awt.Color(204, 204, 204));
        lecturer1Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lecturer1Button.setText("Mr.Vuyisile Memani");
        lecturer1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lecturer1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 111, 176, 45));

        lecturer2Button.setBackground(new java.awt.Color(204, 204, 204));
        lecturer2Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lecturer2Button.setText("Mr.Hans Robert");
        lecturer2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer2ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lecturer2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 110, 175, 47));

        lecturer3Button.setBackground(new java.awt.Color(204, 204, 204));
        lecturer3Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lecturer3Button.setText("Mr.Lekheto");
        lecturer3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer3ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lecturer3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 281, 176, 48));

        lecturer4Button.setBackground(new java.awt.Color(204, 204, 204));
        lecturer4Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lecturer4Button.setText("Mr.Muchenje");
        lecturer4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer4ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lecturer4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 284, 175, 43));

        currentT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        currentT.setText("Time");
        getContentPane().add(currentT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 156, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TutorsPic.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lecturer3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer3ButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
       new Chat().setVisible(true);
    }//GEN-LAST:event_lecturer3ButtonActionPerformed

    private void lecturer2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer2ButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
       new Chat().setVisible(true);
    }//GEN-LAST:event_lecturer2ButtonActionPerformed

    private void lecturer1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer1ButtonActionPerformed
        // TODO add your handling code here:
       setVisible(false);
       new Chat().setVisible(true);
    }//GEN-LAST:event_lecturer1ButtonActionPerformed

    private void lecturer4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer4ButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
       new Chat().setVisible(true);
    }//GEN-LAST:event_lecturer4ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lecturer1Button;
    private javax.swing.JButton lecturer2Button;
    private javax.swing.JButton lecturer3Button;
    private javax.swing.JButton lecturer4Button;
    // End of variables declaration//GEN-END:variables
}
